# Generated by Django 4.2.3 on 2023-07-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('qt_monitor', models.IntegerField(blank=True, null=True)),
                ('qt_notebook', models.IntegerField(blank=True, null=True)),
                ('qt_teclado', models.IntegerField(blank=True, null=True)),
                ('qt_mouse', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorio',
                'ordering': ['id'],
            },
        ),
    ]
