# Generated by Django 4.2.3 on 2023-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_laboratorio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
