# Generated by Django 4.2.3 on 2023-09-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_laboratorio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='qt_monitor',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='qt_mouse',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='qt_notebook',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='qt_teclado',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='qt_maquinas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
