# Generated by Django 4.2.3 on 2023-07-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_inicio', models.DateTimeField()),
                ('hora_inicio', models.TimeField()),
                ('data_fim', models.DateTimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
    ]
