# Generated by Django 4.2.3 on 2023-07-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_fim',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_inicio',
        ),
    ]
