# Generated by Django 4.2.3 on 2023-07-17 13:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorio', '0003_alter_laboratorio_name'),
        ('calendario', '0002_rename_data_fim_agendamento_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['id'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='opicional',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Solicitado', 'Solicitado')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
