# Generated by Django 4.2.3 on 2023-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_alter_agendamento_options_agendamento_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Solicitado', 'Solicitado')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
