# Generated by Django 4.2.3 on 2023-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_agendamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='opicional',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('Aula', 'Aula'), ('Monitoria', 'Monitoria')], max_length=30),
        ),
    ]
