# Generated by Django 4.2.3 on 2023-08-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_alter_agendamento_opicional_alter_agendamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(),
        ),
    ]
