# Generated by Django 4.2.3 on 2023-08-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_alter_agendamento_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
