# Generated by Django 4.2.3 on 2023-08-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_tipo_alter_agendamento_status_alter_agendamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretaria.tipo'),
        ),
    ]
