# Generated by Django 4.2.3 on 2023-08-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_alter_agendamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretaria.tipo'),
        ),
    ]
