# Generated by Django 4.2.3 on 2023-08-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_alter_agendamento_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterField(
            model_name='tipo',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
