# Generated by Django 4.2.3 on 2023-08-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_alter_tipo_options_alter_tipo_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['id'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
    ]
